config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'dashboard_upcoming', to: 'pages#dashboard_upcoming', as: 'dashboard_upcoming'
  get 'dashboard_previous', to: 'pages#dashboard_previous', as: 'dashboard_previous'
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :reviews, only: [:index, :new, :create]
    get 'reviews/new_client_rev', to: 'reviews#new_client_review', as: 'new_client_review' # to be used if we get to create the barber dashboard for the button to rate clients
    resources :services, only: [] do
      resources :appointments, only: [:create]
    end
  end
  resources :appointments, only: [:show] do
    resources :messages, only: [:create]
  end
  get 'appointments/:id/approve', to: 'appointments#approve', as: 'approve_appointment'
  get 'appointments/:id/reject', to: 'appointments#reject', as: 'reject_appointment'
  get 'appointments/:id/pay', to: 'appointments#pay', as: 'pay_appointment'
end

app/views/pages/dashboard.html.erb
<div class="banner barber-page-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_url("cover.png") %>');">

</div>

<div class="container">
  <div class="dashboard-tabs">
    <ul class="list-inline tabs-underlined">
      <li>
        <a href="<%= dashboard_path %>" class="tab-underlined<% if current_page?(controller:"pages", action: "dashboard") %> active<% end %>">Profile</a>
      </li>
      <li>
        <a href="<%= dashboard_upcoming_path %>" class="tab-underlined<% if current_page?(controller:"pages", action: "dashboard_upcoming") %> active<% end %>">Upcoming appointments</a>
      </li>
      <li>
        <a href="<%= dashboard_previous_path %>" class="tab-underlined<% if current_page?(controller:"pages", action: "dashboard_previous") %> active<% end %>">Previous appointments</a>
      </li>
    </ul>
  </div>

  <% if current_page?(controller:"pages", action: "dashboard") %>
  <!-- below the profile pane says barber just because I recycled the code and classes from the barber show page. Here we are talking about a client -->
  <div class="barber-profile-pane">
    <%= image_tag @user.avatar_url , class: 'avatar profile-avatar' %>
    <div class="barber-profile-description">
      <div class="barber-profile-name">
        <h1><%= @user.name %></h1>
      </div>

      <div class="barber-profile-bio">
        <h2>Hey guys, I am <%= @user.name %></h2>
        I am a French guy and therefore I care a lot about my hair. I'm looking for a tailored barbor that could design my next haircut.
      </div>
    </div>
  </div>


  <div class="carousel-and-map-pane">
    <div class="pane-container">
      <div class="container-title">
        <em>My favorite haircuts</em>
      </div>
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
          <% @user.image_urls.each_with_index do |url_obj, i| %>
          <div class="item<% if i == 0 %> active<% end %>" style="background-image: url('<%= image_url(url_obj.url) %>');">
          </div>
          <% end %>
        </div>
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>

  <% unless @reviews.empty? %>
  <h2><br>Reviews</h2>
  <div class="review-cards">
    <% @reviews.each do |review| %>
    <%= render partial: "reviews/review-card", locals: {review: review} %>
    <% end %>
  </div>
  <% end %>
  <% end %>


  <% if current_page?(controller:"pages", action: "dashboard_upcoming") %>
  <h2>Your upcoming appointments</h2>
  <% @appointments.each_with_index do |appt, i| %>
  <%= render 'appointments/appointment-card', appointment: appt, marker: @markers[i] %>
  <% end %>
  <% end %>

  <% if current_page?(controller:"pages", action: "dashboard_previous") %>
  <h2>Your previous appointments</h2>
  <% @appointments.each_with_index do |appt, i| %>
  <%= render 'appointments/appointment-card', appointment: appt, marker: @markers[i] %>
  <% end %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner hompage-banner" style="background-image: linear-gradient(rgba(22,26,38,0.6),rgba(22,26,38,0.6)), url('<%= image_url("cover.png") %>');">
  <div>
    <h1>Great barbers are all around you</h1>
    <div class="homepage-form">
      <%= form_tag users_path, method: :get, id: 'search_form' do %>
      <span class="fas fa-map-marker-alt"></span>
      <%= text_field_tag :query, params[:query], class: "form-control icon", placeholder:" City or barber" %>

      <%= button_tag 'Search', class: 'shortcut-btn', id: 'search_button' %>
      <% end %>
    </div>
  </div>
</div>

<div class="container how-it-works">
  <h2 class="hp-centered">How it works</h2>
  <div class="homepage_how_it_works_row">
    <div class="how-it-works-box">
      <div class="pink-circle"><span>1</span></div>
      <p>Find all great barbers in any city</p>
      <img class="img" src="<%= image_path('magnifier.png') %>" alt="magnifier" height="100" width="100">
    </div>
    <div class="how-it-works-box">
      <div class="pink-circle"><span>2</span></div>
      <p>Select your favorite barber</p>
      <img class="img" src="<%= image_path('heart.png') %>" alt="heart" height="100" width="100">
    </div>
    <div class="how-it-works-box">
      <div class="pink-circle"><span>3</span></div>
      <p>Book online and meet your barber</p>
      <img class="img" src="<%= image_path('booking.png') %>" src="booking.png" alt="booking" height="100" width="100">
    </div>
  </div>
</div>

<div class="pic-and-description">
  <div class="alternate-panes-row">
    <div class="alternate-pane">
      <div class="home-page-pics" style="background-image: linear-gradient(rgba(22,26,38,0.5),rgba(22,26,38,0.5)), url('<%= image_url("homepage-pic-1.png") %>');">
      </div>
    </div>
    <div class="alternate-pane">
      <div class="alternate-text-pane">
        We believe that your haircut is special and your hair deserves the best.
      </div>
    </div>
  </div>

  <div class="alternate-panes-row">
    <div class="alternate-pane">
      <div class="alternate-text-pane">
        ShortCut eases the interraction between professional hairdressers and their customers.
      </div>
    </div>
    <div class="alternate-pane">
      <div class="home-page-pics" style="background-image: linear-gradient(rgba(22,26,38,0.5), rgba(22,26,38,0.5)), url('<%= image_url("homepage-pic-2.png") %>');">
      </div>
    </div>
  </div>

  <div class="alternate-panes-row">
    <div class="alternate-pane">
      <div class="home-page-pics" style="background-image: linear-gradient(rgba(22,26,38,0.5), rgba(22,26,38,0.5)), url('<%= image_url("homepage-pic-3.png") %>');">
      </div>
    </div>
    <div class="alternate-pane">
      <div class="alternate-text-pane">
        We can help you find your favorite barber around the corner with minmial effort and great result.
      </div>
    </div>
  </div>