config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'dashboard_upcoming', to: 'pages#dashboard_upcoming', as: 'dashboard_upcoming'
  get 'dashboard_previous', to: 'pages#dashboard_previous', as: 'dashboard_previous'
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :reviews, only: [:index, :new, :create]
    get 'reviews/new_client_rev', to: 'reviews#new_client_review', as: 'new_client_review' # to be used if we get to create the barber dashboard for the button to rate clients
    resources :services, only: [] do
      resources :appointments, only: [:create]
    end
  end
  resources :appointments, only: [:show] do
    resources :messages, only: [:create]
  end
  get 'appointments/:id/approve', to: 'appointments#approve', as: 'approve_appointment'
  get 'appointments/:id/reject', to: 'appointments#reject', as: 'reject_appointment'
  get 'appointments/:id/pay', to: 'appointments#pay', as: 'pay_appointment'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :service
  belongs_to :barber, class_name: "User"
  belongs_to :client, class_name: "User"
  has_many :messages
  validates :datetime, :location_address, presence: true
  validates :state, inclusion: { in: %w(pending approved rejected paid missed), message: "%{value} is not a valid state" }
  validate :barber_cannot_be_same_as_client

  geocoded_by :location_address, latitude: :location_latitude, longitude: :location_longitude
  after_validation :geocode, if: :will_save_change_to_location_address?

  def service_price
    service.price
  end

  def commute_price
    barber.commute_price
  end
end

private

def barber_cannot_be_same_as_client
  if barber_id == client_id
    errors.add(:barber_same_as_client, "Barber and client cannot be the same")
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: :new
  before_action :set_barber, only: [:new, :create]
  before_action :set_service, only: [:new, :create]

  def show
    @appointment = Appointment.find(params[:id])
    @marker = {
      lng: @appointment.location_longitude,
      lat: @appointment.location_latitude
    }
    @message = Message.new
  end

  def create
    fixed_appt_params = appointment_params
    at_barber_host_location = fixed_appt_params.delete(:at_barber_host_location)
    @appointment = Appointment.new(fixed_appt_params)
    @appointment.client = current_user
    @appointment.service = @service
    @appointment.barber = @service.barber
    if at_barber_host_location
      @appointment.location_address = @user.host_service_address
    else
      @appointment.location_address = appointment_params[:location_address]
    end
    if @appointment.save
      redirect_to appointment_path(@appointment)
    end
  end

  def approve
    Appointment.find(params[:id]).update(state: 'approved')
    redirect_to appointment_path(Appointment.find(params[:id]))
  end

  def reject
    Appointment.find(params[:id]).update(state: 'rejected')
    redirect_to appointment_path(Appointment.find(params[:id]))
  end

  def pay
    Appointment.find(params[:id]).update(state: 'paid')
    redirect_to appointment_path(Appointment.find(params[:id]))
  end

  private

  def set_barber
    @user = User.find(params[:user_id])
  end

  def set_service
    @service = Service.find(params[:service_id])
  end

  def appointment_params
    params.require(:appointment).permit(:location_address, :datetime, :at_barber_host_location)
  end
end

app/views/appointments/_appointment-card.html.erb
<div class="appointment-card">
  <div class="left-content">
    <div class="title-and-icon">
      <div class="state-icon">
        <img src="<%= image_url("state-icon-#{appointment.state}.png") %>">
      </div>
      <div class="card-title">
        <% if appointment.state != 'missed' %>
        <h2>This appointment is: <strong><%= appointment.state %></strong>.</h2>
        <% else %>
        <h2>Oh no, you <strong>missed</strong> this appointment!</h2>
        <% end %>
      </div>
    </div>

    <div class="appointment-info">
      <div class="info-row">
        <div class="info-label">
          Service:
        </div>
        <div class="info">
          <%= appointment.service.title %>
        </div>
      </div>

      <div class="info-row">
        <div class="info-label">
          Barber:
        </div>
        <div class="info">
          <%= appointment.barber.name %>
        </div>
      </div>

      <div class="info-row">
        <div class="info-label">
          Date & time:
        </div>
        <div class="info">
          <%= appointment.datetime.strftime("%e %B %Y at %I:%M %p") %>
        </div>
      </div>

      <div class="info-row">
        <div class="info-label">
          Address:
        </div>
        <div class="info">
          <%= appointment.location_address %>
        </div>
      </div>

      <div class="info-row">
        <div class="info-label">
          Price:
        </div>
        <div class="info">
          <% if appointment.location_address == appointment.barber.host_service_address %>
          € <%= appointment.service.price %>.00
          <% else %>
          <div class="price-sum">
            Service price: € <%= appointment.service.price %>.00<br>
            Commute price: € <%= appointment.barber.commute_price %>.00
          </div>
          <div class="price-total">
            Total: € <%= appointment.service.price + appointment.barber.commute_price %>.00
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <div class="right-content">
    <% if marker %>
    <div
    class="map"
    style="width: 100%; flex: 1;"
    data-markers="<%= marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
    <% end %>

    <!-- All of this will then be conditional on this being an upcoming appointment -->
    <% if appointment.datetime >= Time.now %>
      <% if appointment.state == "paid" %>
      <% elsif appointment.state == "rejected" %>
        <div class="pay-button-container">
          <%= link_to 'PAY', '#', class: 'shortcut-btn disabled' %>
        </div>
      <% elsif appointment.state == "approved"  %>
        <div class="pay-button-container">
          <%= link_to 'PAY', pay_appointment_path(appointment), class: 'shortcut-btn' %>
        </div>
      <% elsif appointment.state == "pending"  %>
        <div class="pay-button-container">
          <%= link_to 'PAY', '#', class: 'shortcut-btn disabled' %>
        </div>
      <% end %>
    <% else %>
      <% if appointment.state == "paid" %>
        <div class="pay-button-container">
          <%= link_to "Review #{appointment.barber.name}", new_user_review_path(appointment.barber), class: 'shortcut-btn' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/appointments/_new.html.erb
New Appointment

<%= simple_form_for [user, service, appointment] do |f| %>
  <% if user.host_service_address && !user.commute_area_address %>
  <input name="appointment[at_barber_host_location]" type="hidden" value="on">
  <p>This barber only receives clients at the address: <%= user.host_service_address %></p>
  <% elsif user.host_service_address %>
  <input name="appointment[at_barber_host_location]" id="at_barber_host_location" type="checkbox">
  <label for="at_barber_host_location">Make an appointment at the barber's location?</label>
  <% else %>
  <p>This barber only commutes to a location you make available. Please insert your location below.</p>
  <% end %>
  <% if user.commute_area_address %>
  <%= f.input :location_address %>
  <% end %>
  <%= datetime_local_field(:appointment, :datetime) %>
  <%= f.submit "Submit", class: "btn btn-danger" %>
<% end %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= simple_form_for [@user, @service, @appointment] do |f| %>
  <% if @user.host_service_address && !@user.commute_area_address %>
  <input name="appointment[at_barber_host_location]" type="hidden" value="on">
  <p>This barber only receives clients at the address: <%= @user.host_service_address %></p>
  <% elsif @user.host_service_address %>
  <input name="appointment[at_barber_host_location]" id="at_barber_host_location" type="checkbox">
  <label for="at_barber_host_location">Make an appointment at the barber's location?</label>
  <% else %>
  <p>This barber only commutes to a location you make available. Please insert your location below.</p>
  <% end %>
  <% if @user.commute_area_address %>
  <%= f.input :location_address %>
  <% end %>
  <%= f.input :datetime %>
  <%= f.submit "Submit", class: "btn btn-danger" %>
<% end %>
<%= link_to 'Go back', root_path %>

app/views/appointments/show.html.erb
<div class="container">
  <%= render 'appointment-card', appointment: @appointment, marker: @marker %>
  <%= render partial: "messages/index", locals: {appointment: @appointment, message: @message} %>
</div>